### ISSUE TITLE
Splitter.Panel.Visible not working on WPF

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto#644]
When setting a Splitter.Panel.Visible=false, the other panel should resize to fill the whole space of the splitter. This works with WinForms and OSX. With WPF the panel just hides and the other one is not resizing.

**Comment by cwensley** [comment]
Hm, I thought I got this working.. have you tried the develop branch?  I added a test specifically for this case so it should be working.

**Comment by TomQv** [comment]
ye, develop branch. It was fixed for Mac, but WPF I never used until now-

**Comment by cwensley** [comment]
Could you make a little test case for your issue?  The test [here](https://github.com/picoe/Eto/blob/develop/Source/Eto.Test/Eto.Test/Sections/Controls/SplitterSection.cs#L452), which sets Splitter.Panel1/2.Visible works for me.

**Comment by TomQv** [comment]
your sample is working, but my usecase is more complex. In our app we need a UI similar to the IDE of Visual Studio with hidable toolwindows at the side and multiple documents in the middle. I'm still not satisfied with what I've reached so far, but I also don't have time for that currently. 
btw. how about multiple toolbars?

**Comment by cwensley** [comment]
Hm, no problem.  I won't be able to fix this without any further detail on why it doesn't work for you, perhaps some hints on what kind of things you do might help.

Multiple toolbars is tracked with issue #339.

**Comment by TomQv** [comment]
The [old sample](https://github.com/picoe/Eto/issues/500#issuecomment-214540995) I did for the same problem with Mac is showing the issue on Wpf.
Hope this helps.

**Comment by cwensley** [comment]
@TomQv thanks for pointing to the sample, but it has too many options for me to know what it is doing.  

Could you tell me what exactly I should be clicking on in the sample and what you expect that is not happening?

**Comment by TomQv** [comment]
sorry ;-)
there is two splitterpanels in the middle. The left one is titled "_xp2" the right one is "_mapWindow1"
With the View-Menu you can change visibility:
- Map:       "_xp2" hidden, "_mapWindow1" visible
- Xplorer:   "_xp2" visible, "_mapWindow1" hidden
- Xplore-Map:   "_xp2" visible, "_mapWindow1" visible
When one gets hidden, the other one must resize to fill the whole space, which is not happening on Wpf, but on WinForms and Osx.
There is also three more splitterpanels which you can hide/view with the View-Menu - Tools left,right,bottom. Same issue.

Tom

**Comment by cwensley** [comment]
@TomQv, great thanks for the explanation, that helps!

I was looking at the toolbars and check boxes and clicking on them and didn't really make sense to me.. and the menu doesn't show the currently selected option for the map/xplorer stuff so it was not quite clear what was going on there.

This should give me enough to look into the issue now, I'll let you know otherwise.

**Comment by cwensley** [comment]
Hey @TomQv, thanks again for posting the issue.  I've hopefully fixed it up, I'll be adding your scenario to Eto.Test soon.  

Basically the Wpf implementation of the Splitter didn't properly recognize when you set the Panel1 or Panel2 to a new control with different visibility, or if you changed the visibility of a panel before the form is shown.

**Comment by TomQv** [comment]
Thanks for the quick fix, its fine now.
