### ISSUE TITLE
Reliably fetching (multiple) selected items in a TreeGridView

### ISSUE THREAD

**Issue by JonSargent** [picoe/Eto#944]
What is the proper way to identify (multiple) selected items in a TreeGridView?

When the tree contains items with children, the SelectedItems property can throw errors when simple methods like .Count() or .ToArray() are called on the (non-null, non-zero-size) collection.  Is this expected?

I had the idea to work around this by using the SelectedRows property instead, and comparing it to a flattened list of (only visible) items -- but I've also found that the item.Expanded property doesn't report correctly in some situations.

Has anyone else encountered this?

Best,

Jon

**Comment by cwensley** [comment]
You're probably running into a bug with MonoMac where it had problems enumerating NSArray (which was the source of SelectedItems on the Mac). This should be fixed in the develop branch.  That is, if you're using Mac and Eto 2.3 which I am assuming as that's the only issue I can think of that relates to this.

P.S. Please use the issue template when submitting issues.  The platform, version, and other details are important to answer your questions.

Hope this helps!

**Comment by JonSargent** [comment]
Thanks, Curtis. And apologies for the incomplete post — I’m using WPF and Eto 2.3. Perhaps I did something strange to cause it.... I’ll post an example tomorrow AM to see if you/others can reproduce. Thanks again for the quick response.

**Comment by JonSargent** [comment]
Here's a code snippet in C#. On my end the test form raises an exception if and only if the child item is selected and the button is clicked.  I'm building against Eto/Eto.Wpf 2.3 using VS 2015 Community (targeting .NET framework 4.5).

`using System.Linq;
using Eto.Drawing;
using Eto.Forms;

namespace MyTestForm
{
    class TestForm : Form
    {
        Button button;
        TreeGridView grid;

        public TestForm()
        {
            ClientSize = new Size(640, 480);
            Title = "TreeGridView";

            // tree grid view
            grid = new TreeGridView();
            grid.AllowMultipleSelection = true;

            // column 1
            var column1 = new GridColumn { HeaderText = "Name" };
            column1.DataCell = new TextBoxCell(0);
            grid.Columns.Add(column1);

            // column 2
            var column2 = new GridColumn { HeaderText = "Property 1" };
            column2.DataCell = new TextBoxCell(1);
            grid.Columns.Add(column2);

            // add one tree grid item with child
            var parent = new TreeGridItem { Values = new string[] { "Parent", "Parent prop 1" }, Expanded = true };
            var child = new TreeGridItem { Values = new string[] { "Child", "Child prop 1" } };
            parent.Children.Add(child);
            grid.DataStore = new TreeGridItemCollection { parent };

            // button
            button = new Button { Text = "Try Me" };
            button.Click += (s, e) =>
            {
                /* NOTE: When child row is selected, .ToArray() raises System.ArgumentOutOfRange exception
                 *       Testing with Eto & Eto.Wpf 2.3, Microsoft Visual C# 2015 (targeting .NET Framework 4.5)
                */
                var items = grid.SelectedItems.ToArray();              
                MessageBox.Show(items.Length + " items selected");
            };

            // layout
            var layout = new DynamicLayout
            {
                Padding = new Padding(10),
                Spacing = new Size(10, 10)
            };
            layout.Add(button);
            layout.Add(grid);
            Content = layout;
        }
    }
}`

**Comment by SlowLogicBoy** [comment]
Strange, it looks like it doesn't like when children are selected.

**Comment by JonSargent** [comment]
Thanks @SlowLogicBoy, unfortunately 2.4.0-build1201 doesn't solve it for me.  When the child is selected I still get the exception.  Selected items occuring _after_ a parent layer -- if that layer is expanded -- also seem to be affected.  For example selecting the "NoChild 2" item throws the exception if and only if the "Parent" layer is expanded:

![treegridview](https://user-images.githubusercontent.com/15347685/34788134-9183ffe0-f5ee-11e7-9985-05247a679ac0.jpg)

So something odd is still going on.  I mentioned in my original post that the item.Expanded property seems capable if misreporting.  I wonder if that might be to blame...

**Comment by JonSargent** [comment]
I previously mentioned that the item.Expanded property is capable of misreporting.  I'm not sure if this is related to the OutOfRange exception, as it seems to occur more rarely.  Specifically, I can induce it by collapsing and then expanding an item whose children have children.  For example, in the TestForm above, replace the tree grid as follows:
`            // add one tree grid item with child, which has a child
            var parent = new TreeGridItem { Values = new string[] { "Parent", "Parent prop 1" }, Expanded = true };
            var child = new TreeGridItem { Values = new string[] { "Child", "Child prop 1" } , Expanded = true };
            var childofchild = new TreeGridItem { Values = new string[] { "Child of child", "Child of child prop 1" } };
            child.Children.Add(childofchild);
            parent.Children.Add(child);
            grid.DataStore = new TreeGridItemCollection { parent };
`

Then try listing visible items with the help of the .Expanded property as follows:
`            button.Click += (s, e) =>
            {
                var visible = new List<TreeGridItem>();
                var collection = (TreeGridItemCollection)grid.DataStore;
                VisibleItemList(collection, ref visible);

                string msg = "";
                foreach (TreeGridItem item in visible)
                {
                    msg += (string)item.Values[0] + " (" + (item.Expanded ? "" : "not ") + "expanded)\n";
                }
                MessageBox.Show(msg);
            };
`

where VisibleItemList is a recursive function:
`        private void VisibleItemList(TreeGridItemCollection collection, ref List<TreeGridItem> items)
        {
            foreach (TreeGridItem item in collection)
            {
                items.Add(item);

                // visible children?
                if (item.Expanded)
                {
                    VisibleItemList(item.Children, ref items);
                }
            }
        }
`

Then run the form, and

1. click the button (all 3 items report -- so far so good)
2. collapse the Parent item
3. click the button again (only the parent item reports -- so far so good)
4. expand the Parent item (hmm, child layer reappears but is collapsed)
5. click the button again (uh oh, child layer misreports as expanded)

Were it not for this issue, I could hack a reliable SelectedItems() method using SelectedRows.

Thanks again,

Jon

**Comment by cwensley** [comment]
@JonSargent see https://help.github.com/articles/creating-and-highlighting-code-blocks/ on how to do multi-line comments.  Three backticks  instead of one ```.  Even better, use ```c#

**Comment by JonSargent** [comment]
Thank you!!! I was just googling how to fix that :)

**Comment by cwensley** [comment]
No problem!  The preview tab when composing the message is helpful for things like that.

**Comment by JonSargent** [comment]
Oops 😊, noted 👍

**Comment by cwensley** [comment]
I've confirmed (finally) that this is only a problem with 2.3.  With the test supplied, it throws an exception in 2.3, but not in 2.4 or in develop branch.

If there are other problems (misreporting expanded property), please file a separate issue if you see any issues with the develop branch (or myget feed)

Thanks again for reporting the issue!  Apologies it took so long to verify.
